package com.demo.task.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiParam;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@ApiModel(description = "Analysis Task Result of a File")
public class TaskResult implements Serializable {
    @ApiParam(name = "Task ID generated by system", format = "UUID", example = "3b38f38e-b727-4c56-942d-8cb0a742790c")
    private String taskID;
    @ApiParam(name = "File ID", format = "UUID", example = "3b38f38e-b727-4c56-942d-8cb0a742790c")
    private String fileID;

    public String getTaskID() {
        return taskID;
    }

    public void setTaskID(String taskID) {
        this.taskID = taskID;
    }

    public String getFileID() {
        return fileID;
    }

    public void setFileID(String fileID) {
        this.fileID = fileID;
    }

    public Date getTaskCreationDate() {
        return taskCreationDate;
    }

    public void setTaskCreationDate(Date taskCreationDate) {
        this.taskCreationDate = taskCreationDate;
    }

    public Date getTaskCompletionDate() {
        return taskCompletionDate;
    }

    public void setTaskCompletionDate(Date taskCompletionDate) {
        this.taskCompletionDate = taskCompletionDate;
    }

    public List<TaskOperationResult> getTaskOperationResultList() {
        return taskOperationResultList;
    }

    public void setTaskOperationResultList(List<TaskOperationResult> taskOperationResultList) {
        this.taskOperationResultList = taskOperationResultList;
    }

    public TaskResult() {
    }

    public TaskStatus getStatus() {
        return status;
    }

    public void setStatus(TaskStatus status) {
        this.status = status;
    }

    private Date taskCreationDate;
    private Date taskCompletionDate;
    List<TaskOperationResult> taskOperationResultList = new ArrayList<>();
    private TaskStatus status;
}
